package com.famviva.camara.data

import android.content.Context
import androidx.annotation.StringRes
import com.famviva.camara.R
import org.json.JSONObject
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale

/** Time-of-day bucket derived from the event hour, used to filter and label. */
enum class DayPeriod(@StringRes val labelRes: Int, val emoji: String, val range: IntRange) {
    LATE_NIGHT(R.string.period_late_night, "🌙", 0..5),
    MORNING(R.string.period_morning, "🌅", 6..11),
    AFTERNOON(R.string.period_afternoon, "☀️", 12..18),
    EVENING(R.string.period_evening, "🌆", 19..23);

    companion object {
        fun of(hour: Int): DayPeriod = entries.first { hour in it.range }
    }
}

/**
 * A motion clip on Drive. The name follows the NVR pattern:
 *   mt_YYYYMMDD_HHMMSS.mp4
 * from which we derive date, time and period without asking Drive for more data.
 */
data class Clip(
    val id: String,
    val name: String,
    val sizeBytes: Long,
    val durationMillis: Long? = null,
    val thumbnailLink: String? = null,
    /** Drive id of our own thumbnail (mt_*.jpg generated by the NVR), if any. */
    val thumbFileId: String? = null,
    /** Motion metrics (from the NVR's metrics.csv), if available. */
    val yavgMax: Double? = null,
    val framesMov: Int? = null,
    /** Exact duration in seconds (from metrics.csv); more reliable than Drive's videoMediaMetadata. */
    val durationSec: Double? = null,
    /** Drive `modifiedTime` = the local file mtime rclone preserved = when the *file* finished being
     *  written (after postroll + muxing). NOT used for the "recording ended" display (that comes from
     *  the filename + duration instead); kept only as raw metadata. */
    val driveModifiedTime: Instant? = null,
    /** Drive `createdTime`: server-assigned at actual upload — when the clip became visible on Drive.
     *  The gap to [recordedEndDateTime] is the real end-to-end upload latency ([uploadDelaySeconds]). */
    val driveCreatedTime: Instant? = null,
) {
    private val stamp: String? =
        Regex("""mt_(\d{8})_(\d{6})""").find(name)?.let { "${it.groupValues[1]}_${it.groupValues[2]}" }

    /** "YYYYMMDD" to group by day; null if the name doesn't match. */
    val dateKey: String? get() = stamp?.substring(0, 8)

    val localDate: LocalDate?
        get() = dateKey?.let { runCatching { LocalDate.parse(it, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull() }

    val localDateTime: LocalDateTime?
        get() = stamp?.let {
            runCatching { LocalDateTime.parse(it, DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) }.getOrNull()
        }

    /**
     * Motion intensity level 1..5 from yavg_max (null if there's no metric):
     *  1 very faint/noise · 2 light (shadow/bug/background) · 3 moderate · 4 notable · 5 strong.
     */
    val intensityLevel: Int? get() = motionIntensityLevel(yavgMax)

    /** "HH:MM:SS" to show the event time. */
    val time: String
        get() = stamp?.let { "${it.substring(9, 11)}:${it.substring(11, 13)}:${it.substring(13, 15)}" } ?: name

    val hour: Int? get() = stamp?.substring(9, 11)?.toIntOrNull()

    val period: DayPeriod? get() = hour?.let { DayPeriod.of(it) }

    /** Direct streaming URL of the binary from the Drive API (requires the Authorization header). */
    val streamUrl: String get() = "https://www.googleapis.com/drive/v3/files/$id?alt=media"

    /** Thumbnail URL: our own jpg if it exists; otherwise Drive's thumbnailLink. */
    val thumbUrl: String?
        get() = when {
            thumbFileId != null -> "https://www.googleapis.com/drive/v3/files/$thumbFileId?alt=media"
            else -> thumbnailLink
        }

    val sizeMb: String get() = "%.1f MB".format(sizeBytes / 1_048_576.0)

    /** Readable duration: "15 s" if <1 min; "m:ss" otherwise. Uses metrics.csv; else videoMediaMetadata. */
    val durationLabel: String?
        get() {
            val s = durationSec?.toInt() ?: durationMillis?.let { (it / 1000).toInt() } ?: return null
            return if (s < 60) "$s s" else "%d:%02d".format(s / 60, s % 60)
        }

    /** Clip length in whole seconds (metrics.csv first, else Drive's videoMediaMetadata). */
    val durationSeconds: Long? get() = durationSec?.toLong() ?: durationMillis?.let { it / 1000 }

    /**
     * When the recorded content actually ends = clip start (from the filename) + duration. This is
     * what you see in the player. We deliberately do NOT use Drive's modifiedTime for this: that's
     * when the *file* finished being written (after postroll + muxing), tens of seconds later.
     */
    val recordedEndDateTime: LocalDateTime?
        get() {
            val start = localDateTime ?: return null
            val dur = durationSeconds ?: return null
            return start.plusSeconds(dur)
        }

    /** "HH:MM:SS" the recorded content ends (local time); null if start/duration unknown. */
    val recordedFinishedTime: String? get() = recordedEndDateTime?.let { "%02d:%02d:%02d".format(it.hour, it.minute, it.second) }

    /** "HH:MM:SS" the clip became visible on Drive (local time), from createdTime; null if absent. */
    val uploadedTime: String? get() = driveCreatedTime?.let { localHms(it) }

    /** Seconds from "content ended" to "visible on Drive" — the real end-to-end latency the user
     *  cares about (covers postroll, muxing, the sync cadence and transfer). Null if unknown. */
    val uploadDelaySeconds: Long?
        get() {
            val end = recordedEndDateTime ?: return null
            val created = driveCreatedTime ?: return null
            val endInstant = end.atZone(ZoneId.systemDefault()).toInstant()
            return Duration.between(endInstant, created).seconds.coerceAtLeast(0)
        }
}

/**
 * Motion intensity 1..5 from yavg_max (null if there's no metric). The single source of truth for
 * the thresholds, shared by [Clip.intensityLevel] (clip list, filter chips) and the background
 * alert-gating in [com.famviva.camara.notify.NewClipsWorker] so both classify identically.
 */
fun motionIntensityLevel(yavgMax: Double?): Int? = yavgMax?.let {
    when {
        it >= 28 -> 5
        it >= 14 -> 4
        it >= 6 -> 3
        it >= 2 -> 2
        else -> 1
    }
}

private fun localHms(i: Instant): String {
    val t = LocalDateTime.ofInstant(i, ZoneId.systemDefault())
    return "%02d:%02d:%02d".format(t.hour, t.minute, t.second)
}

/** "34s" if under a minute, else "m:ss" — for the recording->Drive upload delay. */
fun uploadDelayLabel(seconds: Long): String =
    if (seconds < 60) "${seconds}s" else "%d:%02d".format(seconds / 60, seconds % 60)

/** "4h 20m" / "35m" from a minute count. */
fun formatEta(context: Context, minutes: Int): String {
    val h = minutes / 60
    val m = minutes % 60
    return if (h > 0) context.getString(R.string.battery_eta_hm, h, m)
    else context.getString(R.string.battery_eta_m, m)
}

/**
 * App-side battery ETA (minutes until ~5%) fit over the most recent *discharging* streak in the
 * local history. A robust fallback for when the NVR hasn't reported eta_minutes yet — e.g. right
 * after a charge, when its own rolling window has been reset. Null if not currently discharging or
 * there isn't enough of a downward trend to fit.
 */
fun estimateBatteryEtaMinutes(samples: List<BatterySample>): Int? {
    val streak = samples.takeLastWhile { !it.charging }
    if (streak.size < 2) return null
    val first = streak.first()
    val last = streak.last()
    val hours = (last.epochSec - first.epochSec) / 3600.0
    if (hours <= 0.0) return null
    val drop = (first.battery - last.battery).toDouble()
    if (drop <= 0.0) return null                       // flat or charging — no meaningful ETA
    val ratePerHour = drop / hours
    val remaining = (last.battery - 5).coerceAtLeast(0)
    if (remaining <= 0) return 0
    return ((remaining / ratePerHour) * 60.0).toInt()
}

/** Metrics of a clip read from the NVR's metrics.csv. */
data class ClipMetric(val yavgMax: Double, val framesMov: Int, val durSec: Double?)

/** NVR/camera health, read from the status.json the NVR writes. */
data class CameraHealth(
    val camera: String,
    val ok: Boolean,            // recording_ok: are fresh segments appearing? (what matters)
    val updated: Long,          // epoch (s) of the last report -> heartbeat / "not reporting" detection
    val battery: Int? = null,   // battery % (null if the NVR doesn't report it / no Termux:API)
    val charging: Boolean? = null,
    /** %/h discharge rate, fit by the NVR over a rolling window; null while charging or with too
     *  little history yet. A rough linear estimate, not a precise prediction. */
    val dischargePctPerHour: Double? = null,
    /** Minutes until the battery reaches the NVR's floor threshold (~5%); null under the same
     *  conditions as [dischargePctPerHour]. */
    val etaMinutes: Int? = null,
    /** Recording resolution the NVR is currently using: "2K" (main) or "SUB" (360p fallback when the
     *  2K link is too unstable). null if the NVR doesn't report it (older builds). */
    val recMode: String? = null,
    /** How many times the 2K link flapped (short-lived drops) in the last hour. Visible even while
     *  still recording 2K, as an early "2K is getting unstable" signal. null if not reported. */
    val rec2kDropsLastHour: Int? = null,
    /** Free space (MB) on the phone's recording filesystem. Lets the app warn before a full disk
     *  silently stops recording (the NVR emergency-prunes below its own floor). null if not reported. */
    val diskFreeMb: Int? = null,
) {
    /** true if there's been no report for more than [maxAgeSec] (default 3 h) -> phone probably off.
     *  The NVR heartbeat is every ~20 min and independent of whether there are videos, so "not
     *  reporting" only happens if the phone/NVR actually stopped (not just for lack of motion). */
    fun isStale(nowSec: Long, maxAgeSec: Long = 10800): Boolean = updated > 0 && nowSec - updated > maxAgeSec

    /** Low battery and NOT charging. */
    val lowBattery: Boolean get() = battery != null && battery!! < 30 && charging != true

    /** Recording in the 360p sub-stream because the 2K link was too unstable to hold. Still
     *  recording — just at lower resolution — so this is a warning, not an outage. */
    val recordingInSub: Boolean get() = recMode == "SUB"

    /** The 2K link flapped at least [threshold] times in the last hour (early "2K getting unstable"
     *  signal), even if it's currently back on 2K. */
    fun recording2kUnstable(threshold: Int = 4): Boolean = (rec2kDropsLastHour ?: 0) >= threshold

    /** Recording disk nearly full (below [thresholdMb], default ~1 GB): warn before it fills and the
     *  NVR starts pruning un-uploaded footage to keep recording alive. */
    fun diskLow(thresholdMb: Int = 1024): Boolean = diskFreeMb != null && diskFreeMb!! < thresholdMb

    /** True when the NVR's own ETA estimate is under [thresholdMinutes] (default 2h) — a stronger
     *  signal than [lowBattery] since it accounts for how fast the battery is actually draining. */
    fun etaCritical(thresholdMinutes: Int = 120): Boolean = etaMinutes != null && etaMinutes!! < thresholdMinutes

    /** "4h 20m" / "35m" duration label from [etaMinutes], or null if there's no estimate yet. */
    fun etaLabel(context: Context): String? = etaMinutes?.let { formatEta(context, it) }

    /** "5 min ago" / "2 h ago" since the last report. */
    fun sinceLabel(context: Context, nowSec: Long): String {
        val mins = ((nowSec - updated) / 60).coerceAtLeast(0)
        return when {
            updated <= 0 -> context.getString(R.string.since_no_date)
            mins < 1 -> context.getString(R.string.rel_just_now)
            mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
            else -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        }
    }
}

/** One line of the NVR's events.jsonl outage log. `cam` is null for camera-agnostic services
 *  (sync); `durS` is only set on `up` events (the resolved outage length). */
data class OutageEvent(
    val ts: Long,
    val cam: String?,
    val svc: String,   // recording | segmenter | detector | sync
    val ev: String,    // down | up | drop | error
    val durS: Int? = null,
    val msg: String? = null,
)

/** Parses one events.jsonl line. Returns null for blanks / malformed JSON / missing required
 *  fields, so a bad line never aborts the whole log (parse defensively, line by line). */
fun parseOutageLine(line: String): OutageEvent? {
    val t = line.trim()
    if (!t.startsWith("{")) return null
    return runCatching {
        val j = JSONObject(t)
        val ts = j.optLong("ts", 0L)
        val svc = j.optString("svc").ifBlank { return null }
        val ev = j.optString("ev").ifBlank { return null }
        if (ts <= 0L) return null
        OutageEvent(
            ts = ts,
            cam = if (j.has("cam") && !j.isNull("cam")) j.optString("cam").ifBlank { null } else null,
            svc = svc,
            ev = ev,
            durS = if (j.has("dur_s") && !j.isNull("dur_s")) j.optInt("dur_s") else null,
            msg = if (j.has("msg") && !j.isNull("msg")) j.optString("msg").ifBlank { null } else null,
        )
    }.getOrNull()
}

/** A resolved (or still-ongoing) service outage, paired from a down->up span. */
data class Outage(
    val svc: String,
    val cam: String?,
    val startTs: Long,
    val endTs: Long?,          // null = still down (ongoing)
    val durationSec: Long?,    // known length; null while ongoing
) {
    val ongoing: Boolean get() = endTs == null
}

/** One row of the health timeline: a paired outage span, or a minor drop/error blip. */
sealed interface HealthEvent {
    val ts: Long
}
data class OutageEntry(val outage: Outage) : HealthEvent {
    override val ts: Long get() = outage.startTs
}
data class BlipEntry(val event: OutageEvent) : HealthEvent {
    override val ts: Long get() = event.ts
}

/** Many same-kind blips (a reconnect storm) collapsed into one row, so a flapping link doesn't bury
 *  the real outages under hundreds of near-identical lines. Its ts is the latest blip's. */
data class BlipCluster(
    val svc: String,
    val cam: String?,
    val ev: String,         // drop | error
    val count: Int,
    val firstTs: Long,
    val lastTs: Long,
)
data class BlipClusterEntry(val cluster: BlipCluster) : HealthEvent {
    override val ts: Long get() = cluster.lastTs
}

/**
 * Pairs down->up events per service (+camera) into [Outage] spans and keeps drop/error lines as
 * [BlipEntry]s. A down with no following up is an ongoing outage; an up with no matching down is
 * ignored. Result is newest-first, ready to group by day.
 */
fun buildHealthTimeline(events: List<OutageEvent>): List<HealthEvent> {
    val sorted = events.sortedBy { it.ts }
    val open = HashMap<String, OutageEvent>()   // "svc|cam" -> the still-unmatched down
    val out = mutableListOf<HealthEvent>()
    for (e in sorted) {
        val key = "${e.svc}|${e.cam ?: ""}"
        when (e.ev) {
            "down" -> if (!open.containsKey(key)) open[key] = e   // keep the earliest open down
            "up" -> open.remove(key)?.let { down ->
                val dur = e.durS?.toLong() ?: (e.ts - down.ts).coerceAtLeast(0L)
                out += OutageEntry(Outage(down.svc, down.cam ?: e.cam, down.ts, e.ts, dur))
            }
            else -> out += BlipEntry(e)                            // drop / error / anything unknown
        }
    }
    for ((_, down) in open) out += OutageEntry(Outage(down.svc, down.cam, down.ts, null, null))
    return out.sortedByDescending { it.ts }
}

/**
 * Collapses reconnect storms: runs of at least [minSize] same-(svc, ev, cam) blips within [gapSec]
 * of each other on the same local day become a single [BlipClusterEntry] ("87 detector drops ·
 * 10:46–12:49"). Outages and isolated blips pass through unchanged. Input and output are newest-first.
 */
fun clusterHealthTimeline(
    timeline: List<HealthEvent>,
    gapSec: Long = 900,        // <=15 min between adjacent blips keeps a storm as one run
    minSize: Int = 3,          // fewer than this stays as individual rows (a real pair still reads fine)
): List<HealthEvent> {
    val result = mutableListOf<HealthEvent>()
    result += timeline.filterIsInstance<OutageEntry>()
    // Group blips by kind AND day so a cluster never straddles a day boundary (day-grouped below) or
    // merges different services interleaved during the same storm.
    val blips = timeline.filterIsInstance<BlipEntry>().map { it.event }
    val groups = blips.groupBy { "${it.svc}|${it.ev}|${it.cam ?: ""}|${dateKeyOf(it.ts)}" }
    for ((_, groupEvents) in groups) {
        val sorted = groupEvents.sortedBy { it.ts }
        var i = 0
        while (i < sorted.size) {
            var j = i + 1
            while (j < sorted.size && sorted[j].ts - sorted[j - 1].ts <= gapSec) j++
            val run = sorted.subList(i, j)
            if (run.size >= minSize) {
                val f = run.first()
                result += BlipClusterEntry(BlipCluster(f.svc, f.cam, f.ev, run.size, f.ts, run.last().ts))
            } else {
                run.forEach { result += BlipEntry(it) }
            }
            i = j
        }
    }
    return result.sortedByDescending { it.ts }
}

// ---------------------------------------------------------------------------------------------
// Per-service health timeline ("swimlane") — the "Cobertura por servicio" card on the Salud screen.
// Two data sources feed it: events.jsonl (fine-grained, 24h/7d) reconstructs live state spans, and
// daily_health.jsonl (one rollup line per day, 30d) gives long-horizon coverage without a fat log.
// ---------------------------------------------------------------------------------------------

/** Visual state of a swimlane segment. The concrete colour is chosen in the UI layer (fixed status
 *  hexes), keeping this model UI-agnostic. FLAP_* are "reconnect storm" windows (hatched), not a
 *  clean sustained state; SYNC_WARN is a transient sync error mark. */
enum class LaneState { OK, DEGRADED, DOWN, FLAP_SERIOUS, FLAP_CRITICAL, SYNC_WARN }

/** One contiguous coloured segment on a service lane, [startTs,endTs] in epoch seconds. Its width on
 *  screen is proportional to (endTs-startTs). [flapCount] is the number of drops a FLAP_* span folds. */
data class TimelineSpan(
    val startTs: Long,
    val endTs: Long,
    val state: LaneState,
    val flapCount: Int = 0,
)

/** A single service's reconstructed lane (recording | detector | segmenter | sync) as ordered spans. */
data class ServiceLane(val svc: String, val spans: List<TimelineSpan>)

/** Overall tone for a per-service summary stat (drives its colour: green / amber / red). */
enum class SummaryTone { GOOD, MID, BAD }

/** Per-service summary row for the selected horizon. Only the fields relevant to the service are set;
 *  the UI formats them into a localized "stat + detail" line. */
data class LaneSummary(
    val svc: String,
    val tone: SummaryTone,
    val coveragePct: Double? = null,  // recording lane: % of the window not fully down
    val outageCount: Int = 0,         // recording lane: number of down->up outages
    val worstOutageSec: Long = 0,     // recording lane: longest single outage
    val flapDrops: Int = 0,           // detector/segmenter: total reconnect drops in the window
    val flapDurSec: Long = 0,         // detector/segmenter: total time spent flapping
    val syncErrors: Int = 0,          // sync: number of transient errors
    val worstDate: String? = null,    // 30d: YYYYMMDD of the worst day (recording), if any
)

/** The whole swimlane for a live horizon (24h/7d): the four lanes + their summaries. */
data class ServiceTimeline(
    val windowStart: Long,
    val windowEnd: Long,
    val lanes: List<ServiceLane>,
    val summaries: List<LaneSummary>,
)

private data class LaneInterval(
    val start: Long,
    val end: Long,
    val state: LaneState,
    val priority: Int,       // higher wins on overlap (DOWN 3 > DEGRADED 2 > OK baseline)
    val flapCount: Int = 0,
)

/** Flattens a set of (possibly overlapping, priority-ranked) intervals onto an OK baseline across
 *  [windowStart,windowEnd], producing gap-free non-overlapping spans. Adjacent same-state spans are
 *  coalesced (except distinct FLAP windows, which stay separate). Pure & cheap — run once per horizon,
 *  never per Canvas frame. */
private fun resolveLane(svc: String, windowStart: Long, windowEnd: Long, intervals: List<LaneInterval>): ServiceLane {
    if (windowEnd <= windowStart) return ServiceLane(svc, emptyList())
    val clamped = intervals.mapNotNull {
        val s = it.start.coerceAtLeast(windowStart)
        val e = it.end.coerceAtMost(windowEnd)
        if (e > s) it.copy(start = s, end = e) else null
    }
    val bounds = sortedSetOf(windowStart, windowEnd)
    clamped.forEach { bounds.add(it.start); bounds.add(it.end) }
    val pts = bounds.toList()
    val raw = ArrayList<TimelineSpan>(pts.size)
    for (i in 0 until pts.size - 1) {
        val a = pts[i]; val b = pts[i + 1]
        val mid = (a + b) / 2
        val top = clamped.filter { it.start <= mid && mid < it.end }.maxByOrNull { it.priority }
        raw.add(TimelineSpan(a, b, top?.state ?: LaneState.OK, top?.flapCount ?: 0))
    }
    val merged = ArrayList<TimelineSpan>(raw.size)
    for (s in raw) {
        val last = merged.lastOrNull()
        val isFlap = s.state == LaneState.FLAP_SERIOUS || s.state == LaneState.FLAP_CRITICAL
        if (last != null && !isFlap && last.state == s.state && last.endTs == s.startTs) {
            merged[merged.size - 1] = last.copy(endTs = s.endTs)
        } else merged.add(s)
    }
    return ServiceLane(svc, merged)
}

/** Recording lane intervals: down->up pairs become DOWN (red, priority 3); degraded->restored become
 *  DEGRADED (amber, priority 2). DOWN overrides DEGRADED on overlap. An unpaired down/degraded is
 *  treated as ongoing (extends past the window; the caller clamps). */
private fun recordingIntervals(events: List<OutageEvent>): List<LaneInterval> {
    val rec = events.filter { it.svc == "recording" }.sortedBy { it.ts }
    val out = mutableListOf<LaneInterval>()
    var openDown: Long? = null
    var openDeg: Long? = null
    for (e in rec) {
        when (e.ev) {
            "down" -> if (openDown == null) openDown = e.ts
            "up" -> openDown?.let { out.add(LaneInterval(it, e.ts, LaneState.DOWN, 3)); openDown = null }
            "degraded" -> if (openDeg == null) openDeg = e.ts
            "restored" -> openDeg?.let { out.add(LaneInterval(it, e.ts, LaneState.DEGRADED, 2)); openDeg = null }
        }
    }
    openDown?.let { out.add(LaneInterval(it, Long.MAX_VALUE, LaneState.DOWN, 3)) }
    openDeg?.let { out.add(LaneInterval(it, Long.MAX_VALUE, LaneState.DEGRADED, 2)) }
    return out
}

/** Detector/segmenter lanes flap rather than cleanly go down. Cluster `drop` events within [gapSec]
 *  into flap windows (>= [minSize] drops); severity by drop density (>=30/h or >=60 total = critical,
 *  else serious). Mirrors [clusterHealthTimeline]'s idea but yields drawable spans. */
private fun flapIntervals(
    events: List<OutageEvent>,
    svc: String,
    windowStart: Long,
    windowEnd: Long,
    gapSec: Long = 900,
    minSize: Int = 3,
): List<LaneInterval> {
    val drops = events.filter { it.svc == svc && it.ev == "drop" && it.ts in windowStart..windowEnd }
        .sortedBy { it.ts }
    val out = mutableListOf<LaneInterval>()
    var i = 0
    while (i < drops.size) {
        var j = i + 1
        while (j < drops.size && drops[j].ts - drops[j - 1].ts <= gapSec) j++
        val run = drops.subList(i, j)
        if (run.size >= minSize) {
            val start = run.first().ts
            val end = run.last().ts.coerceAtLeast(start + 1)
            val hours = (end - start) / 3600.0
            val perHour = if (hours > 0) run.size / hours else run.size.toDouble()
            val state = if (perHour >= 30.0 || run.size >= 60) LaneState.FLAP_CRITICAL else LaneState.FLAP_SERIOUS
            out.add(LaneInterval(start, end, state, 2, run.size))
        }
        i = j
    }
    return out
}

/** Sync lane: green baseline with a short amber mark at each transient `error`. */
private fun syncIntervals(events: List<OutageEvent>, windowStart: Long, windowEnd: Long): List<LaneInterval> =
    events.filter { it.svc == "sync" && it.ev == "error" && it.ts in windowStart..windowEnd }
        .map { LaneInterval(it.ts, it.ts + 1, LaneState.SYNC_WARN, 2) }

/**
 * Reconstructs the four service lanes from events.jsonl over a live window and computes per-service
 * summaries. Lane order matches the mockup: recording, detector, segmenter, sync.
 */
fun buildServiceTimeline(events: List<OutageEvent>, windowStart: Long, windowEnd: Long): ServiceTimeline {
    val lanes = listOf(
        resolveLane("recording", windowStart, windowEnd, recordingIntervals(events)),
        resolveLane("detector", windowStart, windowEnd, flapIntervals(events, "detector", windowStart, windowEnd)),
        resolveLane("segmenter", windowStart, windowEnd, flapIntervals(events, "segmenter", windowStart, windowEnd)),
        resolveLane("sync", windowStart, windowEnd, syncIntervals(events, windowStart, windowEnd)),
    )
    val span = (windowEnd - windowStart).coerceAtLeast(1L)
    val summaries = lanes.map { lane ->
        when (lane.svc) {
            "recording" -> {
                val downs = lane.spans.filter { it.state == LaneState.DOWN }
                val degraded = lane.spans.any { it.state == LaneState.DEGRADED }
                val downTotal = downs.sumOf { it.endTs - it.startTs }
                val cov = 100.0 * (span - downTotal) / span
                val worst = downs.maxOfOrNull { it.endTs - it.startTs } ?: 0L
                val tone = when {
                    downs.isEmpty() && !degraded -> SummaryTone.GOOD
                    cov >= 99.5 -> SummaryTone.GOOD
                    cov >= 95.0 -> SummaryTone.MID
                    else -> SummaryTone.BAD
                }
                LaneSummary(lane.svc, tone, coveragePct = cov, outageCount = downs.size, worstOutageSec = worst)
            }
            "detector", "segmenter" -> {
                val flaps = lane.spans.filter { it.state == LaneState.FLAP_SERIOUS || it.state == LaneState.FLAP_CRITICAL }
                val drops = flaps.sumOf { it.flapCount }
                val dur = flaps.sumOf { it.endTs - it.startTs }
                val heavy = flaps.any { it.state == LaneState.FLAP_CRITICAL }
                val tone = if (drops == 0) SummaryTone.GOOD else if (heavy) SummaryTone.BAD else SummaryTone.MID
                LaneSummary(lane.svc, tone, flapDrops = drops, flapDurSec = dur)
            }
            else -> {
                val errs = lane.spans.count { it.state == LaneState.SYNC_WARN }
                LaneSummary(lane.svc, if (errs == 0) SummaryTone.GOOD else SummaryTone.MID, syncErrors = errs)
            }
        }
    }
    return ServiceTimeline(windowStart, windowEnd, lanes, summaries)
}

/** One line of daily_health.jsonl — the NVR's cheap per-day, per-camera health rollup (30d horizon). */
data class DailyHealth(
    val date: String,     // YYYYMMDD
    val cam: String,
    val dayS: Int,        // seconds the day covered (usually 86400; less for a partial today)
    val recDownS: Int,    // seconds recording was fully down
    val recOutages: Int,  // number of recording outages
    val recWorstS: Int,   // longest single outage (s)
    val recSubS: Int,     // seconds recorded in the 360p sub-stream (degraded)
    val detDrops: Int,    // detector reconnect drops
    val segDrops: Int,    // segmenter reconnect drops
    val syncErrors: Int,  // sync transient errors
    val partial: Boolean, // the day's rollup is still accumulating (e.g. today)
)

/** Parses one daily_health.jsonl line; null for blanks / malformed / missing date (parse defensively). */
fun parseDailyHealthLine(line: String): DailyHealth? {
    val t = line.trim()
    if (!t.startsWith("{")) return null
    return runCatching {
        val j = JSONObject(t)
        val date = j.optString("date").ifBlank { return null }
        DailyHealth(
            date = date,
            cam = j.optString("cam", "cam"),
            dayS = j.optInt("day_s", 0),
            recDownS = j.optInt("rec_down_s", 0),
            recOutages = j.optInt("rec_outages", 0),
            recWorstS = j.optInt("rec_worst_s", 0),
            recSubS = j.optInt("rec_sub_s", 0),
            detDrops = j.optInt("det_drops", 0),
            segDrops = j.optInt("seg_drops", 0),
            syncErrors = j.optInt("sync_errors", 0),
            partial = j.optBoolean("partial", false),
        )
    }.getOrNull()
}

/** One day's cell on a 30d lane. [state] is the day's worst state; carries a couple of raw metrics so
 *  the UI can show a localized tap detail (coverage for recording, drop/error counts for the rest). */
data class DayCell(
    val date: String,
    val state: LaneState,
    val partial: Boolean,
    val coveragePct: Double? = null,
    val metric: Int = 0,
    /** Recording lane only: fraction of the full 24 h the NVR was actually alive that day (day_s /
     *  86400). <1.0 means the phone was OFF part of the day — a real footage gap that must NOT be
     *  disguised as OK coverage. 1.0 for other lanes and for a still-accumulating (partial) day. */
    val coveredFrac: Double = 1.0,
)

/** A service's 30d lane as one cell per day. */
data class ServiceDayLane(val svc: String, val cells: List<DayCell>)

/** The whole 30d swimlane: day-cell lanes + per-service summaries. */
data class ServiceDailyTimeline(
    val lanes: List<ServiceDayLane>,
    val summaries: List<LaneSummary>,
    val dayCount: Int,
)

private fun flapStateForCount(drops: Int): LaneState = when {
    drops >= 60 -> LaneState.FLAP_CRITICAL
    drops >= 10 -> LaneState.FLAP_SERIOUS
    else -> LaneState.OK
}

/**
 * Builds the 30d day-cell lanes from daily_health.jsonl, aggregating across cameras per day. Recording
 * colour is by coverage band (>=99.5% green, >=97% amber or notable sub-stream time, else red);
 * detector/segmenter by drop count; sync by error presence. Empty input yields empty lanes (the UI
 * then shows the honest "aún no disponible" note).
 */
fun buildDailyTimeline(days: List<DailyHealth>): ServiceDailyTimeline {
    if (days.isEmpty()) return ServiceDailyTimeline(emptyList(), emptyList(), 0)
    val byDate = days.groupBy { it.date }.toSortedMap()
    val dates = byDate.keys.toList()
    val rec = ArrayList<DayCell>(dates.size)
    val det = ArrayList<DayCell>(dates.size)
    val seg = ArrayList<DayCell>(dates.size)
    val syn = ArrayList<DayCell>(dates.size)
    for (date in dates) {
        val rows = byDate[date]!!
        val dayS = rows.sumOf { it.dayS }.coerceAtLeast(1)
        val downS = rows.sumOf { it.recDownS }
        val subS = rows.sumOf { it.recSubS }
        val cov = 100.0 * (1.0 - downS.toDouble() / dayS)
        val partial = rows.any { it.partial }
        val recState = when {
            cov < 97.0 -> LaneState.DOWN
            cov < 99.5 || subS.toDouble() / dayS >= 0.05 -> LaneState.DEGRADED
            else -> LaneState.OK
        }
        // How much of the full day the NVR was actually alive. For a FINALIZED day, day_s short of
        // 86400 (per cam) means the phone was off part of the day — a real footage gap. A partial
        // (today) day is naturally short because it isn't over, so it doesn't count as a gap.
        val fullDay = 86_400L * rows.size
        val coveredFrac = if (partial) 1.0 else (dayS.toDouble() / fullDay.toDouble()).coerceIn(0.0, 1.0)
        rec.add(DayCell(date, recState, partial, coveragePct = cov, metric = rows.sumOf { it.recOutages }, coveredFrac = coveredFrac))
        val dDrops = rows.sumOf { it.detDrops }
        det.add(DayCell(date, flapStateForCount(dDrops), partial, metric = dDrops))
        val sDrops = rows.sumOf { it.segDrops }
        seg.add(DayCell(date, flapStateForCount(sDrops), partial, metric = sDrops))
        val sErr = rows.sumOf { it.syncErrors }
        syn.add(DayCell(date, if (sErr > 0) LaneState.SYNC_WARN else LaneState.OK, partial, metric = sErr))
    }
    val lanes = listOf(
        ServiceDayLane("recording", rec),
        ServiceDayLane("detector", det),
        ServiceDayLane("segmenter", seg),
        ServiceDayLane("sync", syn),
    )
    // Summaries.
    val avgCov = rec.mapNotNull { it.coveragePct }.average().let { if (it.isNaN()) 100.0 else it }
    val worstDay = days.maxByOrNull { it.recWorstS }
    val recTone = when {
        avgCov >= 99.5 -> SummaryTone.GOOD
        avgCov >= 97.0 -> SummaryTone.MID
        else -> SummaryTone.BAD
    }
    val recSummary = LaneSummary(
        "recording", recTone,
        coveragePct = avgCov,
        outageCount = days.sumOf { it.recOutages },
        worstOutageSec = (worstDay?.recWorstS ?: 0).toLong(),
        worstDate = worstDay?.takeIf { it.recWorstS > 0 }?.date,
    )
    fun flapSummary(svc: String, total: Int, heavyDays: Int) =
        LaneSummary(svc, if (total == 0) SummaryTone.GOOD else if (heavyDays > 0) SummaryTone.BAD else SummaryTone.MID, flapDrops = total)
    val detTotal = days.sumOf { it.detDrops }
    val segTotal = days.sumOf { it.segDrops }
    val syncTotal = days.sumOf { it.syncErrors }
    val summaries = listOf(
        recSummary,
        flapSummary("detector", detTotal, det.count { it.state == LaneState.FLAP_CRITICAL }),
        flapSummary("segmenter", segTotal, seg.count { it.state == LaneState.FLAP_CRITICAL }),
        LaneSummary("sync", if (syncTotal == 0) SummaryTone.GOOD else SummaryTone.MID, syncErrors = syncTotal),
    )
    return ServiceDailyTimeline(lanes, summaries, dates.size)
}

/** Sync-pipeline heartbeat, read from the NVR's sync_status.json. */
data class SyncStatus(
    val updated: Long,
    val lastFastOk: Long,
    val lastHealOk: Long,
    val lastRetentionOk: Long,
    val lastError: String?,
    val lastErrorTs: Long,
) {
    /** No sync heartbeat for more than [maxAgeSec] (default 10 min) -> the sync loop may be stuck. */
    fun isStale(nowSec: Long, maxAgeSec: Long = 600): Boolean = updated > 0 && nowSec - updated > maxAgeSec

    /** A non-empty last_error recorded within [withinSec] (default 6 h) — recent enough to surface. */
    fun hasRecentError(nowSec: Long, withinSec: Long = 21_600): Boolean =
        !lastError.isNullOrBlank() && lastErrorTs > 0 && nowSec - lastErrorTs <= withinSec
}

/** Parses a sync_status.json body; null if it isn't valid JSON. */
fun parseSyncStatus(body: String): SyncStatus? = runCatching {
    val j = JSONObject(body)
    SyncStatus(
        updated = j.optLong("updated", 0L),
        lastFastOk = j.optLong("last_fast_ok", 0L),
        lastHealOk = j.optLong("last_heal_ok", 0L),
        lastRetentionOk = j.optLong("last_retention_ok", 0L),
        lastError = if (j.has("last_error") && !j.isNull("last_error")) j.optString("last_error").ifBlank { null } else null,
        lastErrorTs = j.optLong("last_error_ts", 0L),
    )
}.getOrNull()

/** "HH:MM" (local time) from an epoch-second timestamp. */
fun hourMinuteLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return "%02d:%02d".format(t.hour, t.minute)
}

/** "YYYYMMDD" grouping key for the local day an epoch-second timestamp falls in. */
fun dateKeyOf(epochSec: Long): String =
    LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
        .toLocalDate().format(DateTimeFormatter.BASIC_ISO_DATE)

/** Localized "hace X min / X h / un momento" since an epoch-second timestamp (or "sin fecha"). */
fun agoLabel(context: Context, epochSec: Long, nowSec: Long): String {
    if (epochSec <= 0L) return context.getString(R.string.since_no_date)
    val mins = ((nowSec - epochSec) / 60).coerceAtLeast(0)
    return when {
        mins < 1 -> context.getString(R.string.rel_just_now)
        mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
        else -> context.getString(R.string.rel_hours, (mins / 60).toInt())
    }
}

/** Duration label from a second count: "45s" under a minute, else "4h 20m"/"35m" (via [formatEta]). */
fun formatDurationSec(context: Context, seconds: Long): String =
    if (seconds < 60) "${seconds}s" else formatEta(context, (seconds / 60).toInt())

/** "YYYYMMDD" -> "Today" / "Yesterday" / weekday / "DD/MM/YYYY" (localized). */
fun prettyDate(context: Context, dateKey: String): String {
    val d = runCatching { LocalDate.parse(dateKey, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull()
        ?: return dateKey
    val today = LocalDate.now()
    return when {
        d == today -> context.getString(R.string.date_today)
        d == today.minusDays(1) -> context.getString(R.string.date_yesterday)
        ChronoUnit.DAYS.between(d, today) in 2..6 ->
            d.dayOfWeek.getDisplayName(TextStyle.FULL, Locale.getDefault())
                .replaceFirstChar { it.uppercase() }
        else -> "%02d/%02d/%04d".format(d.dayOfMonth, d.monthValue, d.year)
    }
}

/** "5 min ago" / "3 h ago" / "yesterday 14:30" / "27/06 14:30" (localized). */
fun relativeLabel(context: Context, dt: LocalDateTime, now: LocalDateTime = LocalDateTime.now()): String {
    val mins = ChronoUnit.MINUTES.between(dt, now)
    return when {
        mins < 1 -> context.getString(R.string.rel_just_now)
        mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
        dt.toLocalDate() == now.toLocalDate() -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        dt.toLocalDate() == now.toLocalDate().minusDays(1) ->
            context.getString(R.string.rel_yesterday_time, "%02d:%02d".format(dt.hour, dt.minute))
        else -> "%02d/%02d %02d:%02d".format(dt.dayOfMonth, dt.monthValue, dt.hour, dt.minute)
    }
}

/** "27/06 14:30" from an epoch-second timestamp (local time) — for the battery graph axis. */
fun epochLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return "%02d/%02d %02d:%02d".format(t.dayOfMonth, t.monthValue, t.hour, t.minute)
}

/** Compact axis tick: "HH:MM" for short spans, "DD/MM" once the span crosses a couple of days. */
fun axisTimeLabel(epochSec: Long, longSpan: Boolean): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return if (longSpan) "%02d/%02d".format(t.dayOfMonth, t.monthValue)
    else "%02d:%02d".format(t.hour, t.minute)
}

/** "HH:MM" if the instant is today, else "DD/MM HH:MM" — for the battery "lasts until" forecast. */
fun clockLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return if (t.toLocalDate() == LocalDate.now()) "%02d:%02d".format(t.hour, t.minute)
    else "%02d/%02d %02d:%02d".format(t.dayOfMonth, t.monthValue, t.hour, t.minute)
}

/** Readable byte total (KB/MB/GB). */
fun humanSize(bytes: Long): String = when {
    bytes >= 1_073_741_824 -> "%.2f GB".format(bytes / 1_073_741_824.0)
    bytes >= 1_048_576 -> "%.0f MB".format(bytes / 1_048_576.0)
    else -> "%.0f KB".format(bytes / 1024.0)
}
