package com.famviva.camara.data

import android.content.Context
import androidx.annotation.StringRes
import com.famviva.camara.R
import org.json.JSONObject
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale

/** Time-of-day bucket derived from the event hour, used to filter and label. */
enum class DayPeriod(@StringRes val labelRes: Int, val emoji: String, val range: IntRange) {
    LATE_NIGHT(R.string.period_late_night, "🌙", 0..5),
    MORNING(R.string.period_morning, "🌅", 6..11),
    AFTERNOON(R.string.period_afternoon, "☀️", 12..18),
    EVENING(R.string.period_evening, "🌆", 19..23);

    companion object {
        fun of(hour: Int): DayPeriod = entries.first { hour in it.range }
    }
}

/**
 * A motion clip on Drive. The name follows the NVR pattern:
 *   mt_YYYYMMDD_HHMMSS.mp4
 * from which we derive date, time and period without asking Drive for more data.
 */
data class Clip(
    val id: String,
    val name: String,
    val sizeBytes: Long,
    val durationMillis: Long? = null,
    val thumbnailLink: String? = null,
    /** Drive id of our own thumbnail (mt_*.jpg generated by the NVR), if any. */
    val thumbFileId: String? = null,
    /** Motion metrics (from the NVR's metrics.csv), if available. */
    val yavgMax: Double? = null,
    val framesMov: Int? = null,
    /** Exact duration in seconds (from metrics.csv); more reliable than Drive's videoMediaMetadata. */
    val durationSec: Double? = null,
    /** Drive `modifiedTime` = the local file mtime rclone preserved = when the *file* finished being
     *  written (after postroll + muxing). NOT used for the "recording ended" display (that comes from
     *  the filename + duration instead); kept only as raw metadata. */
    val driveModifiedTime: Instant? = null,
    /** Drive `createdTime`: server-assigned at actual upload — when the clip became visible on Drive.
     *  The gap to [recordedEndDateTime] is the real end-to-end upload latency ([uploadDelaySeconds]). */
    val driveCreatedTime: Instant? = null,
) {
    private val stamp: String? =
        Regex("""mt_(\d{8})_(\d{6})""").find(name)?.let { "${it.groupValues[1]}_${it.groupValues[2]}" }

    /** "YYYYMMDD" to group by day; null if the name doesn't match. */
    val dateKey: String? get() = stamp?.substring(0, 8)

    val localDate: LocalDate?
        get() = dateKey?.let { runCatching { LocalDate.parse(it, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull() }

    val localDateTime: LocalDateTime?
        get() = stamp?.let {
            runCatching { LocalDateTime.parse(it, DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) }.getOrNull()
        }

    /**
     * Motion intensity level 1..5 from yavg_max (null if there's no metric):
     *  1 very faint/noise · 2 light (shadow/bug/background) · 3 moderate · 4 notable · 5 strong.
     */
    val intensityLevel: Int? get() = motionIntensityLevel(yavgMax)

    /** "HH:MM:SS" to show the event time. */
    val time: String
        get() = stamp?.let { "${it.substring(9, 11)}:${it.substring(11, 13)}:${it.substring(13, 15)}" } ?: name

    val hour: Int? get() = stamp?.substring(9, 11)?.toIntOrNull()

    val period: DayPeriod? get() = hour?.let { DayPeriod.of(it) }

    /** Direct streaming URL of the binary from the Drive API (requires the Authorization header). */
    val streamUrl: String get() = "https://www.googleapis.com/drive/v3/files/$id?alt=media"

    /** Thumbnail URL: our own jpg if it exists; otherwise Drive's thumbnailLink. */
    val thumbUrl: String?
        get() = when {
            thumbFileId != null -> "https://www.googleapis.com/drive/v3/files/$thumbFileId?alt=media"
            else -> thumbnailLink
        }

    val sizeMb: String get() = "%.1f MB".format(sizeBytes / 1_048_576.0)

    /** Readable duration: "15 s" if <1 min; "m:ss" otherwise. Uses metrics.csv; else videoMediaMetadata. */
    val durationLabel: String?
        get() {
            val s = durationSec?.toInt() ?: durationMillis?.let { (it / 1000).toInt() } ?: return null
            return if (s < 60) "$s s" else "%d:%02d".format(s / 60, s % 60)
        }

    /** Clip length in whole seconds (metrics.csv first, else Drive's videoMediaMetadata). */
    val durationSeconds: Long? get() = durationSec?.toLong() ?: durationMillis?.let { it / 1000 }

    /**
     * When the recorded content actually ends = clip start (from the filename) + duration. This is
     * what you see in the player. We deliberately do NOT use Drive's modifiedTime for this: that's
     * when the *file* finished being written (after postroll + muxing), tens of seconds later.
     */
    val recordedEndDateTime: LocalDateTime?
        get() {
            val start = localDateTime ?: return null
            val dur = durationSeconds ?: return null
            return start.plusSeconds(dur)
        }

    /** "HH:MM:SS" the recorded content ends (local time); null if start/duration unknown. */
    val recordedFinishedTime: String? get() = recordedEndDateTime?.let { "%02d:%02d:%02d".format(it.hour, it.minute, it.second) }

    /** "HH:MM:SS" the clip became visible on Drive (local time), from createdTime; null if absent. */
    val uploadedTime: String? get() = driveCreatedTime?.let { localHms(it) }

    /** Seconds from "content ended" to "visible on Drive" — the real end-to-end latency the user
     *  cares about (covers postroll, muxing, the sync cadence and transfer). Null if unknown. */
    val uploadDelaySeconds: Long?
        get() {
            val end = recordedEndDateTime ?: return null
            val created = driveCreatedTime ?: return null
            val endInstant = end.atZone(ZoneId.systemDefault()).toInstant()
            return Duration.between(endInstant, created).seconds.coerceAtLeast(0)
        }
}

/**
 * Motion intensity 1..5 from yavg_max (null if there's no metric). The single source of truth for
 * the thresholds, shared by [Clip.intensityLevel] (clip list, filter chips) and the background
 * alert-gating in [com.famviva.camara.notify.NewClipsWorker] so both classify identically.
 */
fun motionIntensityLevel(yavgMax: Double?): Int? = yavgMax?.let {
    when {
        it >= 28 -> 5
        it >= 14 -> 4
        it >= 6 -> 3
        it >= 2 -> 2
        else -> 1
    }
}

private fun localHms(i: Instant): String {
    val t = LocalDateTime.ofInstant(i, ZoneId.systemDefault())
    return "%02d:%02d:%02d".format(t.hour, t.minute, t.second)
}

/** "34s" if under a minute, else "m:ss" — for the recording->Drive upload delay. */
fun uploadDelayLabel(seconds: Long): String =
    if (seconds < 60) "${seconds}s" else "%d:%02d".format(seconds / 60, seconds % 60)

/** "4h 20m" / "35m" from a minute count. */
fun formatEta(context: Context, minutes: Int): String {
    val h = minutes / 60
    val m = minutes % 60
    return if (h > 0) context.getString(R.string.battery_eta_hm, h, m)
    else context.getString(R.string.battery_eta_m, m)
}

/**
 * App-side battery ETA (minutes until ~5%) fit over the most recent *discharging* streak in the
 * local history. A robust fallback for when the NVR hasn't reported eta_minutes yet — e.g. right
 * after a charge, when its own rolling window has been reset. Null if not currently discharging or
 * there isn't enough of a downward trend to fit.
 */
fun estimateBatteryEtaMinutes(samples: List<BatterySample>): Int? {
    val streak = samples.takeLastWhile { !it.charging }
    if (streak.size < 2) return null
    val first = streak.first()
    val last = streak.last()
    val hours = (last.epochSec - first.epochSec) / 3600.0
    if (hours <= 0.0) return null
    val drop = (first.battery - last.battery).toDouble()
    if (drop <= 0.0) return null                       // flat or charging — no meaningful ETA
    val ratePerHour = drop / hours
    val remaining = (last.battery - 5).coerceAtLeast(0)
    if (remaining <= 0) return 0
    return ((remaining / ratePerHour) * 60.0).toInt()
}

/** Metrics of a clip read from the NVR's metrics.csv. */
data class ClipMetric(val yavgMax: Double, val framesMov: Int, val durSec: Double?)

/** NVR/camera health, read from the status.json the NVR writes. */
data class CameraHealth(
    val camera: String,
    val ok: Boolean,            // recording_ok: are fresh segments appearing? (what matters)
    val updated: Long,          // epoch (s) of the last report -> heartbeat / "not reporting" detection
    val battery: Int? = null,   // battery % (null if the NVR doesn't report it / no Termux:API)
    val charging: Boolean? = null,
    /** %/h discharge rate, fit by the NVR over a rolling window; null while charging or with too
     *  little history yet. A rough linear estimate, not a precise prediction. */
    val dischargePctPerHour: Double? = null,
    /** Minutes until the battery reaches the NVR's floor threshold (~5%); null under the same
     *  conditions as [dischargePctPerHour]. */
    val etaMinutes: Int? = null,
    /** Recording resolution the NVR is currently using: "2K" (main) or "SUB" (360p fallback when the
     *  2K link is too unstable). null if the NVR doesn't report it (older builds). */
    val recMode: String? = null,
    /** How many times the 2K link flapped (short-lived drops) in the last hour. Visible even while
     *  still recording 2K, as an early "2K is getting unstable" signal. null if not reported. */
    val rec2kDropsLastHour: Int? = null,
    /** Free space (MB) on the phone's recording filesystem. Lets the app warn before a full disk
     *  silently stops recording (the NVR emergency-prunes below its own floor). null if not reported. */
    val diskFreeMb: Int? = null,
) {
    /** true if there's been no report for more than [maxAgeSec] (default 3 h) -> phone probably off.
     *  The NVR heartbeat is every ~20 min and independent of whether there are videos, so "not
     *  reporting" only happens if the phone/NVR actually stopped (not just for lack of motion). */
    fun isStale(nowSec: Long, maxAgeSec: Long = 10800): Boolean = updated > 0 && nowSec - updated > maxAgeSec

    /** Low battery and NOT charging. */
    val lowBattery: Boolean get() = battery != null && battery!! < 30 && charging != true

    /** Recording in the 360p sub-stream because the 2K link was too unstable to hold. Still
     *  recording — just at lower resolution — so this is a warning, not an outage. */
    val recordingInSub: Boolean get() = recMode == "SUB"

    /** The 2K link flapped at least [threshold] times in the last hour (early "2K getting unstable"
     *  signal), even if it's currently back on 2K. */
    fun recording2kUnstable(threshold: Int = 4): Boolean = (rec2kDropsLastHour ?: 0) >= threshold

    /** Recording disk nearly full (below [thresholdMb], default ~1 GB): warn before it fills and the
     *  NVR starts pruning un-uploaded footage to keep recording alive. */
    fun diskLow(thresholdMb: Int = 1024): Boolean = diskFreeMb != null && diskFreeMb!! < thresholdMb

    /** True when the NVR's own ETA estimate is under [thresholdMinutes] (default 2h) — a stronger
     *  signal than [lowBattery] since it accounts for how fast the battery is actually draining. */
    fun etaCritical(thresholdMinutes: Int = 120): Boolean = etaMinutes != null && etaMinutes!! < thresholdMinutes

    /** "4h 20m" / "35m" duration label from [etaMinutes], or null if there's no estimate yet. */
    fun etaLabel(context: Context): String? = etaMinutes?.let { formatEta(context, it) }

    /** "5 min ago" / "2 h ago" since the last report. */
    fun sinceLabel(context: Context, nowSec: Long): String {
        val mins = ((nowSec - updated) / 60).coerceAtLeast(0)
        return when {
            updated <= 0 -> context.getString(R.string.since_no_date)
            mins < 1 -> context.getString(R.string.rel_just_now)
            mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
            else -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        }
    }
}

/** One line of the NVR's events.jsonl outage log. `cam` is null for camera-agnostic services
 *  (sync); `durS` is only set on `up` events (the resolved outage length). */
data class OutageEvent(
    val ts: Long,
    val cam: String?,
    val svc: String,   // recording | segmenter | detector | sync
    val ev: String,    // down | up | drop | error
    val durS: Int? = null,
    val msg: String? = null,
)

/** Parses one events.jsonl line. Returns null for blanks / malformed JSON / missing required
 *  fields, so a bad line never aborts the whole log (parse defensively, line by line). */
fun parseOutageLine(line: String): OutageEvent? {
    val t = line.trim()
    if (!t.startsWith("{")) return null
    return runCatching {
        val j = JSONObject(t)
        val ts = j.optLong("ts", 0L)
        val svc = j.optString("svc").ifBlank { return null }
        val ev = j.optString("ev").ifBlank { return null }
        if (ts <= 0L) return null
        OutageEvent(
            ts = ts,
            cam = if (j.has("cam") && !j.isNull("cam")) j.optString("cam").ifBlank { null } else null,
            svc = svc,
            ev = ev,
            durS = if (j.has("dur_s") && !j.isNull("dur_s")) j.optInt("dur_s") else null,
            msg = if (j.has("msg") && !j.isNull("msg")) j.optString("msg").ifBlank { null } else null,
        )
    }.getOrNull()
}

/** A resolved (or still-ongoing) service outage, paired from a down->up span. */
data class Outage(
    val svc: String,
    val cam: String?,
    val startTs: Long,
    val endTs: Long?,          // null = still down (ongoing)
    val durationSec: Long?,    // known length; null while ongoing
) {
    val ongoing: Boolean get() = endTs == null
}

/** One row of the health timeline: a paired outage span, or a minor drop/error blip. */
sealed interface HealthEvent {
    val ts: Long
}
data class OutageEntry(val outage: Outage) : HealthEvent {
    override val ts: Long get() = outage.startTs
}
data class BlipEntry(val event: OutageEvent) : HealthEvent {
    override val ts: Long get() = event.ts
}

/** Many same-kind blips (a reconnect storm) collapsed into one row, so a flapping link doesn't bury
 *  the real outages under hundreds of near-identical lines. Its ts is the latest blip's. */
data class BlipCluster(
    val svc: String,
    val cam: String?,
    val ev: String,         // drop | error
    val count: Int,
    val firstTs: Long,
    val lastTs: Long,
)
data class BlipClusterEntry(val cluster: BlipCluster) : HealthEvent {
    override val ts: Long get() = cluster.lastTs
}

/**
 * Pairs down->up events per service (+camera) into [Outage] spans and keeps drop/error lines as
 * [BlipEntry]s. A down with no following up is an ongoing outage; an up with no matching down is
 * ignored. Result is newest-first, ready to group by day.
 */
fun buildHealthTimeline(events: List<OutageEvent>): List<HealthEvent> {
    val sorted = events.sortedBy { it.ts }
    val open = HashMap<String, OutageEvent>()   // "svc|cam" -> the still-unmatched down
    val out = mutableListOf<HealthEvent>()
    for (e in sorted) {
        val key = "${e.svc}|${e.cam ?: ""}"
        when (e.ev) {
            "down" -> if (!open.containsKey(key)) open[key] = e   // keep the earliest open down
            "up" -> open.remove(key)?.let { down ->
                val dur = e.durS?.toLong() ?: (e.ts - down.ts).coerceAtLeast(0L)
                out += OutageEntry(Outage(down.svc, down.cam ?: e.cam, down.ts, e.ts, dur))
            }
            else -> out += BlipEntry(e)                            // drop / error / anything unknown
        }
    }
    for ((_, down) in open) out += OutageEntry(Outage(down.svc, down.cam, down.ts, null, null))
    return out.sortedByDescending { it.ts }
}

/**
 * Collapses reconnect storms: runs of at least [minSize] same-(svc, ev, cam) blips within [gapSec]
 * of each other on the same local day become a single [BlipClusterEntry] ("87 detector drops ·
 * 10:46–12:49"). Outages and isolated blips pass through unchanged. Input and output are newest-first.
 */
fun clusterHealthTimeline(
    timeline: List<HealthEvent>,
    gapSec: Long = 900,        // <=15 min between adjacent blips keeps a storm as one run
    minSize: Int = 3,          // fewer than this stays as individual rows (a real pair still reads fine)
): List<HealthEvent> {
    val result = mutableListOf<HealthEvent>()
    result += timeline.filterIsInstance<OutageEntry>()
    // Group blips by kind AND day so a cluster never straddles a day boundary (day-grouped below) or
    // merges different services interleaved during the same storm.
    val blips = timeline.filterIsInstance<BlipEntry>().map { it.event }
    val groups = blips.groupBy { "${it.svc}|${it.ev}|${it.cam ?: ""}|${dateKeyOf(it.ts)}" }
    for ((_, groupEvents) in groups) {
        val sorted = groupEvents.sortedBy { it.ts }
        var i = 0
        while (i < sorted.size) {
            var j = i + 1
            while (j < sorted.size && sorted[j].ts - sorted[j - 1].ts <= gapSec) j++
            val run = sorted.subList(i, j)
            if (run.size >= minSize) {
                val f = run.first()
                result += BlipClusterEntry(BlipCluster(f.svc, f.cam, f.ev, run.size, f.ts, run.last().ts))
            } else {
                run.forEach { result += BlipEntry(it) }
            }
            i = j
        }
    }
    return result.sortedByDescending { it.ts }
}

/** Sync-pipeline heartbeat, read from the NVR's sync_status.json. */
data class SyncStatus(
    val updated: Long,
    val lastFastOk: Long,
    val lastHealOk: Long,
    val lastRetentionOk: Long,
    val lastError: String?,
    val lastErrorTs: Long,
) {
    /** No sync heartbeat for more than [maxAgeSec] (default 10 min) -> the sync loop may be stuck. */
    fun isStale(nowSec: Long, maxAgeSec: Long = 600): Boolean = updated > 0 && nowSec - updated > maxAgeSec

    /** A non-empty last_error recorded within [withinSec] (default 6 h) — recent enough to surface. */
    fun hasRecentError(nowSec: Long, withinSec: Long = 21_600): Boolean =
        !lastError.isNullOrBlank() && lastErrorTs > 0 && nowSec - lastErrorTs <= withinSec
}

/** Parses a sync_status.json body; null if it isn't valid JSON. */
fun parseSyncStatus(body: String): SyncStatus? = runCatching {
    val j = JSONObject(body)
    SyncStatus(
        updated = j.optLong("updated", 0L),
        lastFastOk = j.optLong("last_fast_ok", 0L),
        lastHealOk = j.optLong("last_heal_ok", 0L),
        lastRetentionOk = j.optLong("last_retention_ok", 0L),
        lastError = if (j.has("last_error") && !j.isNull("last_error")) j.optString("last_error").ifBlank { null } else null,
        lastErrorTs = j.optLong("last_error_ts", 0L),
    )
}.getOrNull()

/** "HH:MM" (local time) from an epoch-second timestamp. */
fun hourMinuteLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return "%02d:%02d".format(t.hour, t.minute)
}

/** "YYYYMMDD" grouping key for the local day an epoch-second timestamp falls in. */
fun dateKeyOf(epochSec: Long): String =
    LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
        .toLocalDate().format(DateTimeFormatter.BASIC_ISO_DATE)

/** Localized "hace X min / X h / un momento" since an epoch-second timestamp (or "sin fecha"). */
fun agoLabel(context: Context, epochSec: Long, nowSec: Long): String {
    if (epochSec <= 0L) return context.getString(R.string.since_no_date)
    val mins = ((nowSec - epochSec) / 60).coerceAtLeast(0)
    return when {
        mins < 1 -> context.getString(R.string.rel_just_now)
        mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
        else -> context.getString(R.string.rel_hours, (mins / 60).toInt())
    }
}

/** Duration label from a second count: "45s" under a minute, else "4h 20m"/"35m" (via [formatEta]). */
fun formatDurationSec(context: Context, seconds: Long): String =
    if (seconds < 60) "${seconds}s" else formatEta(context, (seconds / 60).toInt())

/** "YYYYMMDD" -> "Today" / "Yesterday" / weekday / "DD/MM/YYYY" (localized). */
fun prettyDate(context: Context, dateKey: String): String {
    val d = runCatching { LocalDate.parse(dateKey, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull()
        ?: return dateKey
    val today = LocalDate.now()
    return when {
        d == today -> context.getString(R.string.date_today)
        d == today.minusDays(1) -> context.getString(R.string.date_yesterday)
        ChronoUnit.DAYS.between(d, today) in 2..6 ->
            d.dayOfWeek.getDisplayName(TextStyle.FULL, Locale.getDefault())
                .replaceFirstChar { it.uppercase() }
        else -> "%02d/%02d/%04d".format(d.dayOfMonth, d.monthValue, d.year)
    }
}

/** "5 min ago" / "3 h ago" / "yesterday 14:30" / "27/06 14:30" (localized). */
fun relativeLabel(context: Context, dt: LocalDateTime, now: LocalDateTime = LocalDateTime.now()): String {
    val mins = ChronoUnit.MINUTES.between(dt, now)
    return when {
        mins < 1 -> context.getString(R.string.rel_just_now)
        mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
        dt.toLocalDate() == now.toLocalDate() -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        dt.toLocalDate() == now.toLocalDate().minusDays(1) ->
            context.getString(R.string.rel_yesterday_time, "%02d:%02d".format(dt.hour, dt.minute))
        else -> "%02d/%02d %02d:%02d".format(dt.dayOfMonth, dt.monthValue, dt.hour, dt.minute)
    }
}

/** "27/06 14:30" from an epoch-second timestamp (local time) — for the battery graph axis. */
fun epochLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return "%02d/%02d %02d:%02d".format(t.dayOfMonth, t.monthValue, t.hour, t.minute)
}

/** Compact axis tick: "HH:MM" for short spans, "DD/MM" once the span crosses a couple of days. */
fun axisTimeLabel(epochSec: Long, longSpan: Boolean): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return if (longSpan) "%02d/%02d".format(t.dayOfMonth, t.monthValue)
    else "%02d:%02d".format(t.hour, t.minute)
}

/** "HH:MM" if the instant is today, else "DD/MM HH:MM" — for the battery "lasts until" forecast. */
fun clockLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return if (t.toLocalDate() == LocalDate.now()) "%02d:%02d".format(t.hour, t.minute)
    else "%02d/%02d %02d:%02d".format(t.dayOfMonth, t.monthValue, t.hour, t.minute)
}

/** Readable byte total (KB/MB/GB). */
fun humanSize(bytes: Long): String = when {
    bytes >= 1_073_741_824 -> "%.2f GB".format(bytes / 1_073_741_824.0)
    bytes >= 1_048_576 -> "%.0f MB".format(bytes / 1_048_576.0)
    else -> "%.0f KB".format(bytes / 1024.0)
}
