package com.famviva.camara.data

import android.content.Context
import androidx.annotation.StringRes
import com.famviva.camara.R
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale

/** Time-of-day bucket derived from the event hour, used to filter and label. */
enum class DayPeriod(@StringRes val labelRes: Int, val emoji: String, val range: IntRange) {
    LATE_NIGHT(R.string.period_late_night, "🌙", 0..5),
    MORNING(R.string.period_morning, "🌅", 6..11),
    AFTERNOON(R.string.period_afternoon, "☀️", 12..18),
    EVENING(R.string.period_evening, "🌆", 19..23);

    companion object {
        fun of(hour: Int): DayPeriod = entries.first { hour in it.range }
    }
}

/**
 * A motion clip on Drive. The name follows the NVR pattern:
 *   mt_YYYYMMDD_HHMMSS.mp4
 * from which we derive date, time and period without asking Drive for more data.
 */
data class Clip(
    val id: String,
    val name: String,
    val sizeBytes: Long,
    val durationMillis: Long? = null,
    val thumbnailLink: String? = null,
    /** Drive id of our own thumbnail (mt_*.jpg generated by the NVR), if any. */
    val thumbFileId: String? = null,
    /** Motion metrics (from the NVR's metrics.csv), if available. */
    val yavgMax: Double? = null,
    val framesMov: Int? = null,
    /** Exact duration in seconds (from metrics.csv); more reliable than Drive's videoMediaMetadata. */
    val durationSec: Double? = null,
    /** Drive `modifiedTime` = the local file mtime rclone preserved = when the *file* finished being
     *  written (after postroll + muxing). NOT used for the "recording ended" display (that comes from
     *  the filename + duration instead); kept only as raw metadata. */
    val driveModifiedTime: Instant? = null,
    /** Drive `createdTime`: server-assigned at actual upload — when the clip became visible on Drive.
     *  The gap to [recordedEndDateTime] is the real end-to-end upload latency ([uploadDelaySeconds]). */
    val driveCreatedTime: Instant? = null,
) {
    private val stamp: String? =
        Regex("""mt_(\d{8})_(\d{6})""").find(name)?.let { "${it.groupValues[1]}_${it.groupValues[2]}" }

    /** "YYYYMMDD" to group by day; null if the name doesn't match. */
    val dateKey: String? get() = stamp?.substring(0, 8)

    val localDate: LocalDate?
        get() = dateKey?.let { runCatching { LocalDate.parse(it, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull() }

    val localDateTime: LocalDateTime?
        get() = stamp?.let {
            runCatching { LocalDateTime.parse(it, DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) }.getOrNull()
        }

    /**
     * Motion intensity level 1..5 from yavg_max (null if there's no metric):
     *  1 very faint/noise · 2 light (shadow/bug/background) · 3 moderate · 4 notable · 5 strong.
     */
    val intensityLevel: Int?
        get() = yavgMax?.let {
            when {
                it >= 28 -> 5
                it >= 14 -> 4
                it >= 6 -> 3
                it >= 2 -> 2
                else -> 1
            }
        }

    /** "HH:MM:SS" to show the event time. */
    val time: String
        get() = stamp?.let { "${it.substring(9, 11)}:${it.substring(11, 13)}:${it.substring(13, 15)}" } ?: name

    val hour: Int? get() = stamp?.substring(9, 11)?.toIntOrNull()

    val period: DayPeriod? get() = hour?.let { DayPeriod.of(it) }

    /** Direct streaming URL of the binary from the Drive API (requires the Authorization header). */
    val streamUrl: String get() = "https://www.googleapis.com/drive/v3/files/$id?alt=media"

    /** Thumbnail URL: our own jpg if it exists; otherwise Drive's thumbnailLink. */
    val thumbUrl: String?
        get() = when {
            thumbFileId != null -> "https://www.googleapis.com/drive/v3/files/$thumbFileId?alt=media"
            else -> thumbnailLink
        }

    val sizeMb: String get() = "%.1f MB".format(sizeBytes / 1_048_576.0)

    /** Readable duration: "15 s" if <1 min; "m:ss" otherwise. Uses metrics.csv; else videoMediaMetadata. */
    val durationLabel: String?
        get() {
            val s = durationSec?.toInt() ?: durationMillis?.let { (it / 1000).toInt() } ?: return null
            return if (s < 60) "$s s" else "%d:%02d".format(s / 60, s % 60)
        }

    /** Clip length in whole seconds (metrics.csv first, else Drive's videoMediaMetadata). */
    val durationSeconds: Long? get() = durationSec?.toLong() ?: durationMillis?.let { it / 1000 }

    /**
     * When the recorded content actually ends = clip start (from the filename) + duration. This is
     * what you see in the player. We deliberately do NOT use Drive's modifiedTime for this: that's
     * when the *file* finished being written (after postroll + muxing), tens of seconds later.
     */
    val recordedEndDateTime: LocalDateTime?
        get() {
            val start = localDateTime ?: return null
            val dur = durationSeconds ?: return null
            return start.plusSeconds(dur)
        }

    /** "HH:MM:SS" the recorded content ends (local time); null if start/duration unknown. */
    val recordedFinishedTime: String? get() = recordedEndDateTime?.let { "%02d:%02d:%02d".format(it.hour, it.minute, it.second) }

    /** "HH:MM:SS" the clip became visible on Drive (local time), from createdTime; null if absent. */
    val uploadedTime: String? get() = driveCreatedTime?.let { localHms(it) }

    /** Seconds from "content ended" to "visible on Drive" — the real end-to-end latency the user
     *  cares about (covers postroll, muxing, the sync cadence and transfer). Null if unknown. */
    val uploadDelaySeconds: Long?
        get() {
            val end = recordedEndDateTime ?: return null
            val created = driveCreatedTime ?: return null
            val endInstant = end.atZone(ZoneId.systemDefault()).toInstant()
            return Duration.between(endInstant, created).seconds.coerceAtLeast(0)
        }
}

private fun localHms(i: Instant): String {
    val t = LocalDateTime.ofInstant(i, ZoneId.systemDefault())
    return "%02d:%02d:%02d".format(t.hour, t.minute, t.second)
}

/** "34s" if under a minute, else "m:ss" — for the recording->Drive upload delay. */
fun uploadDelayLabel(seconds: Long): String =
    if (seconds < 60) "${seconds}s" else "%d:%02d".format(seconds / 60, seconds % 60)

/** "4h 20m" / "35m" from a minute count. */
fun formatEta(context: Context, minutes: Int): String {
    val h = minutes / 60
    val m = minutes % 60
    return if (h > 0) context.getString(R.string.battery_eta_hm, h, m)
    else context.getString(R.string.battery_eta_m, m)
}

/**
 * App-side battery ETA (minutes until ~5%) fit over the most recent *discharging* streak in the
 * local history. A robust fallback for when the NVR hasn't reported eta_minutes yet — e.g. right
 * after a charge, when its own rolling window has been reset. Null if not currently discharging or
 * there isn't enough of a downward trend to fit.
 */
fun estimateBatteryEtaMinutes(samples: List<BatterySample>): Int? {
    val streak = samples.takeLastWhile { !it.charging }
    if (streak.size < 2) return null
    val first = streak.first()
    val last = streak.last()
    val hours = (last.epochSec - first.epochSec) / 3600.0
    if (hours <= 0.0) return null
    val drop = (first.battery - last.battery).toDouble()
    if (drop <= 0.0) return null                       // flat or charging — no meaningful ETA
    val ratePerHour = drop / hours
    val remaining = (last.battery - 5).coerceAtLeast(0)
    if (remaining <= 0) return 0
    return ((remaining / ratePerHour) * 60.0).toInt()
}

/** Metrics of a clip read from the NVR's metrics.csv. */
data class ClipMetric(val yavgMax: Double, val framesMov: Int, val durSec: Double?)

/** NVR/camera health, read from the status.json the NVR writes. */
data class CameraHealth(
    val camera: String,
    val ok: Boolean,            // recording_ok: are fresh segments appearing? (what matters)
    val updated: Long,          // epoch (s) of the last report -> heartbeat / "not reporting" detection
    val battery: Int? = null,   // battery % (null if the NVR doesn't report it / no Termux:API)
    val charging: Boolean? = null,
    /** %/h discharge rate, fit by the NVR over a rolling window; null while charging or with too
     *  little history yet. A rough linear estimate, not a precise prediction. */
    val dischargePctPerHour: Double? = null,
    /** Minutes until the battery reaches the NVR's floor threshold (~5%); null under the same
     *  conditions as [dischargePctPerHour]. */
    val etaMinutes: Int? = null,
) {
    /** true if there's been no report for more than [maxAgeSec] (default 3 h) -> phone probably off.
     *  The NVR heartbeat is every ~20 min and independent of whether there are videos, so "not
     *  reporting" only happens if the phone/NVR actually stopped (not just for lack of motion). */
    fun isStale(nowSec: Long, maxAgeSec: Long = 10800): Boolean = updated > 0 && nowSec - updated > maxAgeSec

    /** Low battery and NOT charging. */
    val lowBattery: Boolean get() = battery != null && battery!! < 30 && charging != true

    /** True when the NVR's own ETA estimate is under [thresholdMinutes] (default 2h) — a stronger
     *  signal than [lowBattery] since it accounts for how fast the battery is actually draining. */
    fun etaCritical(thresholdMinutes: Int = 120): Boolean = etaMinutes != null && etaMinutes!! < thresholdMinutes

    /** "4h 20m" / "35m" duration label from [etaMinutes], or null if there's no estimate yet. */
    fun etaLabel(context: Context): String? = etaMinutes?.let { formatEta(context, it) }

    /** "5 min ago" / "2 h ago" since the last report. */
    fun sinceLabel(context: Context, nowSec: Long): String {
        val mins = ((nowSec - updated) / 60).coerceAtLeast(0)
        return when {
            updated <= 0 -> context.getString(R.string.since_no_date)
            mins < 1 -> context.getString(R.string.rel_just_now)
            mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
            else -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        }
    }
}

/** "YYYYMMDD" -> "Today" / "Yesterday" / weekday / "DD/MM/YYYY" (localized). */
fun prettyDate(context: Context, dateKey: String): String {
    val d = runCatching { LocalDate.parse(dateKey, DateTimeFormatter.BASIC_ISO_DATE) }.getOrNull()
        ?: return dateKey
    val today = LocalDate.now()
    return when {
        d == today -> context.getString(R.string.date_today)
        d == today.minusDays(1) -> context.getString(R.string.date_yesterday)
        ChronoUnit.DAYS.between(d, today) in 2..6 ->
            d.dayOfWeek.getDisplayName(TextStyle.FULL, Locale.getDefault())
                .replaceFirstChar { it.uppercase() }
        else -> "%02d/%02d/%04d".format(d.dayOfMonth, d.monthValue, d.year)
    }
}

/** "5 min ago" / "3 h ago" / "yesterday 14:30" / "27/06 14:30" (localized). */
fun relativeLabel(context: Context, dt: LocalDateTime, now: LocalDateTime = LocalDateTime.now()): String {
    val mins = ChronoUnit.MINUTES.between(dt, now)
    return when {
        mins < 1 -> context.getString(R.string.rel_just_now)
        mins < 60 -> context.getString(R.string.rel_minutes, mins.toInt())
        dt.toLocalDate() == now.toLocalDate() -> context.getString(R.string.rel_hours, (mins / 60).toInt())
        dt.toLocalDate() == now.toLocalDate().minusDays(1) ->
            context.getString(R.string.rel_yesterday_time, "%02d:%02d".format(dt.hour, dt.minute))
        else -> "%02d/%02d %02d:%02d".format(dt.dayOfMonth, dt.monthValue, dt.hour, dt.minute)
    }
}

/** "27/06 14:30" from an epoch-second timestamp (local time) — for the battery graph axis. */
fun epochLabel(epochSec: Long): String {
    val t = LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSec), ZoneId.systemDefault())
    return "%02d/%02d %02d:%02d".format(t.dayOfMonth, t.monthValue, t.hour, t.minute)
}

/** Readable byte total (KB/MB/GB). */
fun humanSize(bytes: Long): String = when {
    bytes >= 1_073_741_824 -> "%.2f GB".format(bytes / 1_073_741_824.0)
    bytes >= 1_048_576 -> "%.0f MB".format(bytes / 1_048_576.0)
    else -> "%.0f KB".format(bytes / 1024.0)
}
